In [10]:
import numpy as np

class Matrix:
    def __init__(self, matrix):
        self.matrix = np.array(matrix)

    def max_min_element(self):
        return self.matrix.max(), self.matrix.min()

    def transpose(self):
        return self.matrix.T

    def multiply(self, other):
        return np.dot(self.matrix, other)

    def add(self, other):
        return np.add(self.matrix, other)

if __name__ == "__main__":
    A = Matrix([
        [34, 100, 12],
        [72, 24, 55],
        [61, 20, 19]
    ])

    max_element, min_element = A.max_min_element()
    print(f"Elemen terbesar: {max_element}, Elemen terkecil: {min_element}")

    T = A.transpose()
    print(f"Transpose of A:\n{T}")

    product = A.multiply(T)
    print(f"Perkalian A dan T:\n{product}")

    sum = A.add(T)
    print(f"Penjumlahan A dan T:\n{sum}")


Elemen terbesar: 100, Elemen terkecil: 12
Transpose of A:
[[ 34  72  61]
 [100  24  20]
 [ 12  55  19]]
Perkalian A dan T:
[[11300  5508  4302]
 [ 5508  8785  5917]
 [ 4302  5917  4482]]
Penjumlahan A dan T:
[[ 68 172  73]
 [172  48  75]
 [ 73  75  38]]
